Mein Branch into master -> Branch von Rasmus und Hannes zsm gefasst
Kjubbe/Kniffel_ITD3-03_SwT pull request #5
Opened 2020-11-08 13:07 UTC by nilsweichler

2020-11-08 13:24 UTC, hanneshargus commented on src/view/GameView.java
> +        turnFinished = new javax.swing.JButton();
turnFinished zu turnFinishedButton ändern

2020-11-08 13:24 UTC, hanneshargus commented on src/view/GameView.java
> +        chooseField = new javax.swing.JButton();
chooseField zu chooseFieldButton ändern

2020-11-09 08:38 UTC, Kjubbe requested changes
Die Karte sollte (meiner Meinung nach) nicht in zwei Menüs aufgeteilt sein. Es sollte eine Tabelle für die gesamte Karte geben. Außerdem sollte die Spaltengröße etwas angepasst werden.
Wir können ebenfalls über die Notwendigkeit der Doppelpunkte nach den Feldnamen debattieren.
Spätere Änderungen werden ja auch Daten der Karten-Klasse nutzen, da können dann ja auch die Kartennamen hergenommen werden.
Die neusten Commits beinhalten auch JUnit-Tests, die vorallem hilfreich sind, wenn ihr das Hinzufügen von Spielern in eure View testet, obwohl diese Logik noch nicht implementiert ist. Genauso ist es z.B. bei der Datenbank auch.
Bezüglich der 23 Anmerkungen: bitte in Zukunft etwas mehr aufpassen und drüberschauen, später braucht ihr dafür auch JUnit Tests, vllt. daher auch etwas früher fertigstellen :D 

EDIT: Bitte nutzt das "Resolve conversation", sobald eine Anmerkung gefixt ist, bzw. fügt zu meinem Kommentar eure Kommentare hinzu, wenn ihr euch auf eine bestimmte Sache hinweisen wollt

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +    }
Die `main` Methode muss hier raus, wir können nur eine in `Main.java` haben

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +                {"Bonus bei über 63:", null},
Ändern in `"Bonus bei min. 63:"`

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +                {"Gesamt:", null},
Umbennen in "Zwischensumme"

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        jTablePart2.setToolTipText("PART2");
Der Tooltip sollte klein geschrieben werden

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        turnFinished.setText("Zug beenden");
Der "Zug Beenden Button" ist bei dieser View noch nicht sinnvoll.
Der Zug wird immer mit
1. dem Streichen einer Karte
2. dem Ausfüllen einer Karte
beendet.

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        ExitButton.setText("Spiel abbrechen");
Der Exit-Button sollte als letzter Punkt in der Liste stehen.
Er sollte ebenfalls etwas deutlicher benannt werden, z.B. `"Zurück zum Hauptmenü"`

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        Player1Button.setText("Spieler 1");
Ihr hardcoded die Spieler hier in die Leiste. Die Spieler müssen jedoch variabel (z.B. per Methode) dem Menü hinzugefügt werden. Die hardcoded Spieler können ja erstmal bestehen bleiben, jedoch sollte schonmal das Grundgerüst dafür stehen, dass Spieler in die Leiste hinzugefügt werden können.

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        File.setText("Spiel");
Umbenennen in `"Optionen"`

2020-11-09 08:38 UTC, Kjubbe commented on src/view/GameView.java
> +        jMenuBar1.add(File);
Die Optionen sollten sich visuell von den Spielern abheben. Sie sollten vllt.
- etwas Abstand zu den Spielern haben oder
- die Spieler an der rechten Seite von rechts nach links aufgelistet sein.

Dadurch ist alles auch etwas mehr balanciert

2020-11-09 09:43 UTC, nilsweichler commented
Danke Kjell :) @hanneshargus @Rasmushibra Soll ich das machen die changes oder will einer von euch das machen?
@Kjubbe achte ich nächstes mal drauf bevor ich die zusammen merge 👍

2020-11-09 12:24 UTC, hanneshargus commented
Die Namen der Felder hab ich mehrmals geändert, da ich versucht habe diese aus der Card, bzw. Field Klasse zu ziehen, habe es jedoch nicht hinbekommen, werde das noch in der Konferenz nachfragen, wo mein Fehler liegt. Die fehlerhaften Bezeichnungen werde ich dann ebenfalls ersetzen.
Die Karte an sich können wir auch als eine Tabelle darstellen, habe es für mich sinnlich getrennt. Werde ich zu einer Tabelle zusammenfassen macht mehr Sinn.
Der Button "Zug beendet" macht kein Sinn, da hast du Recht, werde ich entfernen.
Ich werde nächstes Mal sorgfältiger arbeiten.

2020-11-15 10:27 UTC, Kjubbe requested changes

2020-11-15 10:27 UTC, Kjubbe commented on src/Main.java
> +                new GameView().setVisible(true);
`GameView` sollte nicht in der `Main` erstellt werden
`setVisible` kann in den Konstruktor der `GameView`

2020-11-15 10:27 UTC, Kjubbe commented on src/game/Card.java
> +	public static final Field[] fields = { new Field("Nur Einser Zählen"), new Field("Nur Zweier Zählen"),
Das Array an Feldern darf nicht statisch sein, da jede Karte ihr eigenes Array an Feldern haben muss. Erstellt stattdessen ein statisches `String`-Array mit allen Namen und nutzt eine Referenz auf diese

2020-11-15 10:27 UTC, Kjubbe commented on src/view/GameView.java
> +        playercard.setToolTipText("PART2");
ToolTipText fehlerhaft

2020-11-15 10:27 UTC, Kjubbe commented on src/view/GameView.java
> +                {"Endsumme:", null}
Umbennen in `"Gesamtsumme"`

2020-11-15 10:27 UTC, Kjubbe commented on src/view/GameView.java
> +        playercard.setToolTipText("playercard");
Der ToolTipText ist der Text der auftaucht, wenn über das Element mit der Maus gehovered wird. Dieser Text sollte also auch auf Deutsch sein, wie z.B. `"Spielerkarte"`

2020-11-30 10:38 UTC, Kjubbe requested changes
Die Bilder der Würfel im Ordner `diece` sollten entfernt werden.
Die neuen Bilder im Ordner `rescources` sollten eindeutiger bennannt werden wie z.B.
`die1.png`, etc. oder nicht-umbenannt in einem Ordner `rescources/dice` liegen

2020-11-30 10:38 UTC, Kjubbe commented on src/view/LoginScreenView.java
> +
Dem `LoginScreen` fehlt noch ein Registrieren Button.

2020-11-30 10:38 UTC, Kjubbe commented on src/view/LoginScreenView.java
> +    }
`Main Methode` darf nicht doppelt vorkommen

2020-11-30 10:38 UTC, Kjubbe commented on src/view/LoginScreenView.java
> +        jLabel3.setText("KNIFFEL - THE GAME");
Der `LoginScreen` sollte simpler sein. Jetzt gerade sieht es aus wie ein Hauptmenü.

2020-11-30 10:38 UTC, Kjubbe commented on src/view/StatistikDialogView.java
> +    }
Doppelte `Main` Methode

2020-11-30 10:38 UTC, Kjubbe commented on src/view/StatistikSpeichernView.java
> +    }
Doppelte `Main` Methode

2020-11-30 10:38 UTC, Kjubbe commented on src/view/StatistikSpeichernView.java
> +public class StatistikSpeichernView extends javax.swing.JFrame {
Diese Klasse wird nicht benötigt. Die Statistik wird immer lokal gespeichert und die Wahl zwischen speichern und nicht speichern sollte mit einer Simplen Checkbox im `LoginScreen` gemacht werden

2020-11-30 12:59 UTC, Fokarr commented on src/view/LoginScreenView.java
> +        jLabel3.setText("KNIFFEL - THE GAME");
Was könnte man denn entfernen?

2020-11-30 19:59 UTC, Kjubbe requested changes

2020-11-30 19:59 UTC, Kjubbe commented on src/view/LoginScreenView.java
> +        jLabel3.setText("KNIFFEL - THE GAME");
Es sollte nicht `"Kniffel - The Game"` beim Login stehen. Sowas gehört in den `StartScreen`. Da könnte so eine Überschrift hin wie `"Spieler hinzufügen"` oder so :D

2021-01-03 13:43 UTC, Kjubbe approved these changes

2021-01-03 13:46 UTC, merged